### ISSUE TITLE
ipfs daemon (manual build & config)

### ISSUE THREAD

**Issue by General-Beck** [airalab/robonomics-tools#6]
Ubuntu 18.04 
ipfs from snap - `snap install ipfs`
1. `Error: cannot connect to the api. Is the deamon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api`
`
ipfs no init. make `ipfs init`
2. `Error: cannot connect to the api. Is the deamon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api`
xrtd: fd:16: Data.ByteString.hGetLine: end of file`
start daemon with `ipfs daemon --enable-pubsub-experiment`
MB add to Readme/Wiki?

**Comment by akru** [comment]
Added troubleshooting section, please feel free to add new points:
https://github.com/airalab/robonomics-tools#33-troubleshooting
